### ISSUE TITLE
Determinar arquitetura

### ISSUE THREAD

**Issue by dyegoreisa** [p4p4l4gu4x/gabaritoExtraOficial#1]
Definir a arquitetura a ser usada

**Comment by p4p4l3gu4x** [comment]
Arquitetura será Spring Boot + Spring JPA + Spring MVC +  + Angular.
O banco de dados escolhido é o Mongo DB por facilidade de utilização das tecnicas de Map e Reduce para determinar o gabarito extraoficial.
